name: pokedex

networks:
  pokenet:

volumes:
  postgres-data:

services:
   postgres:
    container_name: database
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: poke_app_dev
    networks:
      - pokenet
